application: username-generator
version: 1
runtime: php
api_version: 1

handlers:
- url: /stylesheets
  static_dir: web/stylesheets

- url: /javascripts
  static_dir: web/javascripts

- url: /images
  static_dir: web/images

- url: /fonts
  static_dir: web/fonts

- url: /(.*)
  script: web/index.php
